class map as "ObjectMap <i>id:2000</i>" {
    {field}._slots : {
    {field}\t'a': 0,
    {field}\t'a:': 1,
    {field}\t'value': 2
    {field}}
    ._parent_slots : {'p*': 0}
    .primitive_code : None
    .parameters : [ ]
}

class another_map as "ObjectMap <i>id:<b>2001</b></i>" {
    {field}._slots : {
    {field}\t'a': 0,
    {field}\t'a:': 1,
    {field}\t'value': 2,
    {field}\t<b>'b': 3</b>
    {field}}
    ._parent_slots : {'p*': 0}
    .primitive_code : None
    .parameters : [ ]
}


class obj as "Object <i>id:100</i>" {
    {field}.map : ObjectMap(id:2000)
    {field}.scope_parent : None
    {field}._slot_values : [
    {field}\tPrimitiveIntObject(1),
    {field}\tObject(id:50),
    {field}\tPrimitiveIntObject(2),
    {field}]
    {field}._parent_slot_values : [
    {field}\tObject(id:99)
    {field}]
}

class another_obj as "Object <i>id:101</i>" {
    {field}.map : ObjectMap(id:<b>2001</b>)
    {field}.scope_parent : None
    {field}._slot_values : [
    {field}\tPrimitiveIntObject(5),
    {field}\tObject(id:50),
    {field}\tPrimitiveIntObject(2),
    {field}\t<b>PrimitiveIntObject(3)</b>
    {field}]
    {field}._parent_slot_values : [
    {field}\tObject(id:99)
    {field}]
}


obj -u-> map: use
another_obj -u-> another_map: use
obj -r[hidden]- another_obj